#pragma once

#include "auto_unregister.h"
#include "closure.h"
#include "cmd_line.h"
#include "image_ole_i.h"
#include "ipc_manager.h"
#include "log.h"
#include "misc_thread.h"
#include "pin_yin_helper.h"
#include "ring.h"
#include "templated_object_factory.h"
#include "threads.h"
#include "tool.h"
#include "utf8_file_util.h"
#include "util.h"
#include "zoom_image.h"
